name: Github Actions Demo
on: 
  push:
    branches:
    - main
    paths-ignore: 
    - .github/**
  pull_request:
    branches: 
    - main
  schedule:
    - cron: "15 6 7 * *"
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_REF
          ls -al
